name: PHPUnit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 8.1, 8.2]
        prefer: [prefer-lowest, prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.prefer }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }} and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          composer-cache: true

      - name: Install dependencies
        run: composer install --prefer-${{ matrix.prefer }} --no-interaction --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
