# name: run-tests

# on: [push, pull_request]

# jobs:
#   test:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       fail-fast: false
#       matrix:
#         os: [ubuntu-latest]
#         php: [8.2, 8.1]
#         dependency-version: [prefer-lowest, prefer-stable]

#     name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup PHP
#         uses: shivammathur/setup-php@v2
#         with:
#           php-version: ${{ matrix.php }}
#           extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
#           coverage: xdebug

#       - name: Install dependencies
#         run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

#       - name: Run tests
#         run: vendor/bin/phpunit --no-coverage

name: PHPUnit

on: [push, pull_request]
jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [8.1, 8.2]
        prefer: [lowest, stable]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php${{ matrix.php }}-${{ matrix.prefer }}-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php${{ matrix.php }}-${{ matrix.prefer }}-
            ${{ runner.os }}-php${{ matrix.php }}-
            ${{ runner.os }}-

      - name: Install dependencies
        run: composer update --prefer-${{ matrix.prefer }} --no-interaction --no-ansi

      - name: Run PHPUnit with code coverage
        run: vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml
